# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ea98d518a719f6d645eabc1296a89b5"
name = "B2B-Customers-Lists"
handle = "b2b-customers-lists"
application_url = "https://spectrum-earrings-restrict-comics.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "b2b-approved-lists.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_locations,read_metaobject_definitions,read_metaobjects,read_products,write_customers,write_metaobject_definitions,write_metaobjects"

[auth]
redirect_urls = [
  "https://spectrum-earrings-restrict-comics.trycloudflare.com/auth/callback",
  "https://spectrum-earrings-restrict-comics.trycloudflare.com/auth/shopify/callback",
  "https://spectrum-earrings-restrict-comics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
