# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "924a2a75e24cee1a989490dc9ae87ee3"
name = "b2b-customer-lists"
handle = "b2b-customer-lists"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,write_customers,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions,write_locations,read_locations,read_customers,write_customers"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
